spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inflean
    username: root
    password: 131wnsdn

server:
  port: 8081
  servlet:
    session:
      timeout: 30m
# mybatis:
#   mapper-locations: mappers/MenuMapper.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: kr.board.springmvc01.entity

